yiisoft/yii2-elasticsearch

ActiveRecord.php, Command.php, Connection.php, Query.php, QueryBuilder.php, README.md, docs/guide-ja/README.md, docs/guide-ja/usage-ar.md, docs/guide/README.md, docs/guide/usage-ar.md
Blog post - https://www.elastic.co/blog/elastic-you-know-for-more-than-search
For the guide sections HTTPS protocol is disabled, that's why only homepage refers to https page.
=> Elasticsearch site moved to elastic.co [ci skip]

CHANGELOG.md, Connection.php
The code is tested and works as expected.
I'm not sure whether it can be covered by unit tests because it requires special ES server configuration. We can not mock it because CURL options are never exposed from the `httpRequest()`
=> Elasticsearch auth implemented

Query.php, QueryBuilder.php
Just found that `min_score` was missing from Query. `min_score` can be useful if you want to exclude documents which have a `_score` less than a minimum threshold.
See: http://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-min-score.html
Example usage:
```
$query->minScore(0.5);
```
=> Add support for min_score

ActiveQuery.php, ActiveRecord.php, BatchQueryResult.php, CHANGELOG.md, Command.php, Query.php, tests/QueryTest.php
Hi!
I've implemented my own version of batch query for elasticsearch. It is consistent with other db classes. In other words, batch query processing is done with `batch()` and `each()` functions. Also, I've written some tests for this functionality.
I would love to see this commit merged into trunk, because then I shall be able to fix issues #48 and #19.
=> Alternative scoll/scan implementation

DebugPanel.php
Is it OK to update these classes? Without them this toolbar panel looks broken in yii 2.0.7.
=> updated debug panel classes to be consistent with yii 2.0.7

ActiveRecord.php, BulkCommand.php, CHANGELOG.md, Connection.php
My implementation of Bulk command API. Typical usage:
```php
$bulkCommand = $db->createBulkCommand();
$bulkCommand->addAction(["update" => [/* ... */], ["doc" => /* ... */]]);
$bulkCommand->addDeleteAction(123, 'my_index', 'my_type');
$bulkCommand->addDeleteAction(456, 'my_index', 'my_other_type');
$result = $bulkCommand->execute();
```
Methods like `addUpdateAction`, `addIndexAction`, and `addCreateAction` could be implemented later if necessary (but I doubt we can make them more convenient than the generic `addAction` method, so I wouldn't bother).
=> Bulk command API

ActiveDataProvider.php, ActiveRecord.php, CHANGELOG.md
If a model extending the ActiveRecord class does not implement the primaryKey function, the primary key will default to '_id'.  However, this property is inaccessible as it is private, resulting in an UnknownPropertyException.  The accessibility of the property would need to be changed to protected, or an accessor method would need to be implemented (which I chose). 
To reproduce the bug that this PR fixes:
1. Create a new model and extend the ActiveRecord
2. Use the default primary key (_id)/don't override the primaryKey method
3. Attempt to use ActiveDataProvider
=> added accessor for default primary key

.travis.yml, ActiveRecord.php, BatchQueryResult.php, Command.php, Connection.php, Query.php, QueryBuilder.php, tests/ActiveRecordTest.php, tests/ElasticsearchTargetTest.php, tests/QueryBuilderTest.php, tests/QueryTest.php, tests/data/ar/Animal.php, tests/data/ar/Customer.php, tests/data/ar/Item.php, tests/data/ar/Order.php, tests/data/ar/OrderItem.php, tests/data/config.php
| New feature?  | yes/no
| Breaks BC?    | yes
| Fixed issues  | #112
Notes:
- removed Query::filter()
- queries can be set through either `Query::query()` or through `Query::where()`
- rewrite `QueryBuilder` condition building to support Elasticsearch 5.0. All the where params are wrapped into `constant_score` query
- optimized `Query::andWhere()` and `Query::orWhere()` so it won't generate unnecessary subqueries on subsequent calls.
- remove `Query::fields()` (fields query part is removed in favor of stored_fields and works differently in 5.0)
- add `Query::storedFields()`, `Query::scriptFields()`
- reset`CURL_POSTFIELDS` in `Connection::resetCurlHandle()`, it was causing test errors in 5.4 (because in …
=> Elasticsearch 5.x support

ActiveRecord.php
Refers to #118. Put back `$options` param.
Put-if-absent behavior is retained for active records with primary key. Though, I am not sure it should be so cause it's not default behavior in elasticsearch.
=> Put back $options param in ActiveRecord::insert()

Connection.php
since elasticsearch 6, content type is mandatory. Otherwise, requests will all fail.
https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests
| Breaks BC?    | yes
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> since elasticsearch 6, content type is mandatory

Command.php
Since es 1.5.3 deleting document by query [was depricated](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/docs-delete-by-query.html), in 2.0 was removed.
In v5.0 we should use [DeleteByQuery API](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/docs-delete-by-query.html) insted.
Otherwise we must have [delete_by_query plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/plugins-delete-by-query.html) installed.
=> using _delete_by_query insted depricated _query

docs/guide-fr/usage-ar.md, docs/guide-ja/usage-ar.md, docs/guide/usage-ar.md
| Tests pass?   | -
Since 5th version of Elasticsearch the `fuzzy_like_this` query has been removed. Take a look [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-flt-query.html).
Now we should use `fuzziness` parameter for `match` query.
=> Fix code example in documentaion of using fuzziness

docs/guide-ja/mapping-indexing.md, docs/guide/mapping-indexing.md
| Tests pass?   | -
| Fixed issues  | none
Since 5-th version of ElasticSearch [new data types is used](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html). In particular `text` or `keyword` type should be used instead of `string` type.
But on docs from 2.1 branch still used old data types.
=> fix data types in docs from string to text

CHANGELOG.md, DebugPanel.php
This pr fixes the "Bad Request (#400): Unable to verify your data submission." error when using the "run query" action in the debugger details panel by registering the YiiAsset in order to inject csrf token in ajax requests
=> Bugfix: Fixed "Bad Request" on "run query" in debug panel

ActiveRecord.php, CHANGELOG.md, Connection.php, Query.php, QueryBuilder.php
| Breaks BC?    | yes
| Tests pass?   | no
| Fixed issues  | no
InvalidParamException is deprecated since 2.0.14. 
Use `InvalidArgumentException` instead.
=>  InvalidParamException to InvalidArgumentException

ActiveDataProvider.php
Fix the return value of prepareTotalCount() in ActiveDataProvider to support elasticsearch 7.x
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> Fix prepareTotalCount() support ElasticSearch 7.x

Query.php
=> make `count()` code in `Query` consistent with `ActiveDataProvider`

docs/guide-ja/mapping-indexing.md, docs/guide-ru/mapping-indexing.md, docs/guide/mapping-indexing.md
With the old example i get this error:
Elasticsearch request failed with code 400. Response body:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters
| Is bugfix    |  yes
| New feature  | no
| Breaks BC    | no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> change mapping-indexing example

CHANGELOG.md, Query.php
The source field can be set to `false` in which case no source will be returned (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html#source-filtering).
Before this fix when passing `false` to the `source` function it would be passed as an array (`[false]` by Yii to ElasticSearch. This would cause ElasticSearch to treat it as field which it tries to match. Since there is often no field called 'false' no source is returned. Therefore it might seem that the old code works, but since ElasticSearch does try to find the non-existing field for each document this has a huge performance impact. On a small test index it …
=> Fixed Query::source() when $source = `false`

ActiveDataProvider.php, CHANGELOG.md
| Fixed issues  | https://github.com/yiisoft/yii2/pull/18560
This fixes regression introduced in https://github.com/yiisoft/yii2/pull/18476
Should we create branch 2.0.x for previous versions of ES and push this change there as well to release v2.0.8? I don't see 2.0.x to be tested with Github workflow as well.
=> Connection class added (2.1.x)

BulkCommand.php, Command.php, composer.json
- adds `ext-mbstring` and `ext-json` to composer.json as  requirements.
- fixes missing phpdocs and a small typo.
| Fixed issues  |
=> Few updates to phpdoc, and add missing requirements to composer.json

.github/workflows/build.yml, CHANGELOG.md, Query.php, QueryBuilder.php, docs/guide/usage-query.md, tests/QueryTest.php
| Breaks BC?    | no? Requires Elasticsearch version 7.11 or higher 
Added query config to support [Runtime Fields/Mappings](https://www.elastic.co/guide/en/elasticsearch/reference/current/runtime.html) in Elasticsearch 7.11 and newer.
=> Added Runtime Mappings

CHANGELOG.md, Connection.php, composer.json
| Is bugfix?    | ❌
| New feature?  | ✔️
| Fixed issues  | 
Hi, in elasticsearch is enabled security by default since version 8.0, but there's no way to configure this client to make it work. So I added extra attribute to allow further configuration of curl session. I considered adding new attribute per curl option, but this way is more flexible.
=> Curl options config

CHANGELOG.md, Connection.php
| Is bugfix?    | ✔️
| New feature?  | ❌
| Fixed issues  |  #329, #330 
Fix curl options merging as integer keys are discarded with `array_merge`
=> Fix curlOptions merging

BulkCommand.php, CHANGELOG.md
| Is bugfix?    | ✔️
| New feature?  | ❌
This PR disables JSON pretty print for ElasticSearch bulk API since it uses new lines as delimiter.
From the [ElasticSearch bulk API documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#:~:text=Because%20this%20format%20uses%20literal%20%5Cn%27s%20as%20delimiters%2C%20make%20sure%20that%20the%20JSON%20actions%20and%20sources%20are%20not%20pretty%20printed.):
> Because this format uses literal \n's as delimiters, make sure that the JSON actions and sources are not pretty printed.
=> Disable JSON pretty print for ElasticSearch bulk API

CHANGELOG.md, src/Query.php, src/QueryBuilder.php
| Is bugfix?    | ❌
| New feature?  | ✔️
| Fixed issues  | #352
=> Fix #352: Add support for query parameter `search_after` to paginate over large datasets
