docs/guide-ja/usage-ar.md

And also the character encoding fixed to utf-8

docs/guide-ja/usage-ar.md links to elasticsearch fixed [ci skip]

---

Command.php

Add functions:
- `updateSettings()` for update settings of indices
- `updateAnalyzers` for update analysis of indices , as a special case.

Fix TODO indices-update-settings

---

tests/ConnectionTest.php
tests/data/config.php

Also updated phpDoc for `config-local.php `

Added ConnectionTest

---

docs/guide-ja/README.md
docs/guide-ja/usage-data-providers.md

Japanese translation of the document updated.

docs/guide-ja/usage-data-providers.md added [ci skip]

---

CHANGELOG.md
docs/guide/README.md
docs/guide/mapping-indexing.md
docs/guide/usage-ar.md

updated guide (#60)

---

docs/guide-ja/README.md
docs/guide-ja/mapping-indexing.md
docs/guide-ja/usage-ar.md
docs/guide-ja/usage-data-providers.md
docs/guide/usage-ar.md

documentation fixed and ja translation updated

documentation fixed and ja translation updated [ci skip]

---

CHANGELOG.md
QueryBuilder.php
tests/QueryBuilderTest.php

I've done some minor cleanup and added tests. Also I've reverted this commit: https://github.com/yiisoft/yii2-elasticsearch/pull/76/commits/5f51c73c296254394f95c2c70da21d9d073f117a.
If we do need to modify cURL code, let's do it in another PR.

Support for half-bounded range operators

---

Query.php

| Tests pass?   | no
| Fixed issues  | #91, #59 
Added nested aggregation support

Nested aggregation

---

CHANGELOG.md
Connection.php
tests/ConnectionTest.php

| Fixed issues  | Supercedes PR #94 (I hope)

Allow to connect to ES cluster using HTTPS

---

CHANGELOG.md
ElasticsearchTarget.php
tests/ElasticsearchTargetTest.php

Enhanced log target originally implemented by @trntv.
Context logging is optional and optionally embeddable into every message. Where possible, data is logged as arrays for better analysis using Kibana.

New log target

---

ElasticsearchTarget.php

| Fixed issues  | no
Correct usage of cacheContext in getContextMessage()

Correct usage of cacheContext

---

CHANGELOG.md
DebugPanel.php

| Fixed issues  | no
Can view debug panel with latest base debug panel yii styling class

Fix view debug panel with. 2.0.10 version

---

Query.php

Fixing some broken links to Elasticsearch docs in code comments.

Fixing broken elasticsearch doc links in comments

---

BatchQueryResult.php
CHANGELOG.md
QueryBuilder.php
composer.json

Fixes #149

---

BatchQueryResult.php
CHANGELOG.md
QueryBuilder.php
composer.json

Changed `yii\base\Object` to `yii\base\BaseObject`

---

.github/ISSUE_TEMPLATE.md
docs/guide/installation.md

Fix spelling

---

docs/guide/installation.md

| Fixed issues  | https://github.com/yiisoft/yii2-elasticsearch/issues/192

modify README(issue #192)

---

ActiveDataProvider.php
CHANGELOG.md

fix infinite loop

---

.travis.yml
composer.json

Experiment to fix tests

---

docs/guide/mapping-indexing.md

Closes #218
| Is bugfix?    | No
| New feature?  | No
| Breaks BC?    | No
| Tests pass?   | 
| Fixed issues  | #218

Comment out invalid syntax in sample [skip ci]

---

docs/guide-ja/mapping-indexing.md

| Tests pass?   | --
| Fixed issues  | guide-ja updated

docs/guide-ja/mapping-indexing.md updated [ci skip]

---

CHANGELOG.md
Query.php
QueryBuilder.php

| Breaks BC?    | ?
| Fixed issues  | add collapse to query

add collapse support

---

Query.php
docs/guide/usage-ar.md

| Tests pass?   | should
* Fix `addStatisticalFacet()` examples
* Remove `@param string $type` from `addAggregate()` docblock
* Reformat Query.php comments to not exceed 80 characters per line (PSR-2)

Fix and reformat some docs

---

.travis.yml
composer.json

Travis adjustments

---

README.md

add note delete-by-query plugin

---

.travis.yml

Use phpunit from vendor

---

.travis.yml
composer.json
tests/bootstrap.php
tests/compatibility.php

[2.1] Use phpunit from vendor

---

DebugPanel.php

Added missing `use` statement
| Fixed issues  | #227

Added missing `use` statement

---

docs/guide-ja/installation.md

| Tests pass?   | --
| Fixed issues  | guide-ja updated

docs/guide-ja/installation.md updated [ci skip]

---

DebugPanel.php

Fix panel asset

---

docs/guide-ja/usage-ar.md

| Tests pass?   | --
| Fixed issues  | --

docs/guide-ja/usage-ar.md updated [ci skip]

---

ActiveQuery.php
CHANGELOG.md
tests/ActiveQueryTest.php

Fix for #191

---

CHANGELOG.md
QueryBuilder.php
tests/QueryTest.php

Fix issue #171 (allow query() and where() in Query)

---

README.md

Add dslVersion to README in Configuration section

add dslVersion to README

---

tests/ActiveDataProviderTest.php

| Fixed issues  | 
Add new test for Aggregations

add aggregation test

---

ActiveDataProvider.php
docs/guide/usage-ar.md
docs/guide/usage-data-providers.md
tests/ActiveRecordTest.php

| Is bugfix?    | yes/no
| Fixed issues  |

add suggestion getter to  ActiveDataProvider,add suggestion unitTest

---

Command.php
tests/QueryTest.php

| Breaks BC?    | yes
| Fixed issues  | #216

Fix suggester

---

docs/guide/installation.md
docs/guide/usage-ar.md
docs/guide/usage-data-providers.md
docs/guide/usage-query.md

| Tests pass?   | -
Some words/verses have been fixed in the English guide.

Doc fix 2020-08 [ci skip]

---

ActiveDataProvider.php
CHANGELOG.md

Reverted changes

---

CHANGELOG.md
Connection.php
composer.json

| Fixed issues  | related to https://github.com/yiisoft/yii2/pull/18817

Use `random_int()` when choosing connection

---

Connection.php

| Tests pass?   | no
| Fixed issues  | renewed the old url which is not important

replace the old elastic search url with new one

---

.github/workflows/build.yml
Command.php
ElasticsearchTarget.php

| Is bugfix?    | ❌
| New feature?  | ✔️
| Fixed issues  | https://github.com/yiisoft/yii2-elasticsearch/pull/321#issuecomment-1126816080

Replace services with docker-run.

---

QueryBuilder.php
tests/QueryBuilderTest.php

| Is bugfix?    | ❌
| New feature?  | ✔️
| Fixed issues  |

implemented match,match_pharse in Query::where()

---

docs/guide-fr/installation.md
docs/guide-ja/installation.md
docs/guide-ru/installation.md
docs/guide/installation.md

| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii2-elasticsearch/issues/338

update docs folder links

---

tests/ActiveRecordTestTrait.php
tests/data/ar/ActiveRecord.php
tests/data/ar/Animal.php
tests/data/ar/Cat.php

| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii2-elasticsearch/issues/340

update tests folder links

---

Command.php
Connection.php
README.md
composer.json

| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii2-elasticsearch/issues/342

update root folder links
